#!/usr/bin/env bash
# Aenternis — install Rust 1.83 toolchain into a Cowork sandbox container.
#
# The sandbox is allowed to reach Ubuntu archives but rust-lang.org and
# sh.rustup.rs are blocked, so `rustup` is unusable. Ubuntu 22.04 universe
# happens to ship rustc-1.83 / cargo-1.83 / rustfmt-1.83 / clippy 0.1.83 as
# separate packages. Without sudo we can still `apt download` the .deb
# archives and extract them into a local prefix.
#
# Usage (run once per fresh sandbox session):
#
#     bash scripts/install-rust-sandbox.sh
#     source "$HOME/rust-apt/env"
#     rustc --version  # → 1.83.0
#
# After sourcing env, all four tools (rustc, cargo, rustfmt, clippy) are on
# PATH and shared libs resolve via LD_LIBRARY_PATH. The install survives
# until the sandbox is recycled at session end.
#
# Idempotent: re-running is fast — apt download skips existing archives,
# dpkg-deb -x is a no-op if the layout already exists.
#
# Exit code:
#     0  — toolchain ready, env file written
#     1  — at least one step failed; check stderr

set -u
set -o pipefail

PREFIX="${RUST_SANDBOX_PREFIX:-$HOME/rust-apt}"
RUST_VER="1.83"

mkdir -p "${PREFIX}"
cd "${PREFIX}"

# Quick exit if already installed and working.
if [ -x "${PREFIX}/usr/lib/rust-${RUST_VER}/bin/rustc" ]; then
    if "${PREFIX}/usr/lib/rust-${RUST_VER}/bin/rustc" --version 2>/dev/null \
         | grep -q "rustc ${RUST_VER}"; then
        echo "[install-rust-sandbox] already installed at ${PREFIX} — skipping download"
        echo "[install-rust-sandbox] source ${PREFIX}/env to use it"
        exit 0
    fi
fi

# Rust toolchain debs from Ubuntu 22.04 universe.
RUST_PKGS=(
    rustc-${RUST_VER}
    cargo-${RUST_VER}
    rustfmt-${RUST_VER}
    rust-${RUST_VER}-clippy
    libstd-rust-${RUST_VER}
    libstd-rust-${RUST_VER}-dev
)

# Shared lib transitive closure that cargo & rustc actually load at runtime.
# Curated by trial; ldd will complain if any future Ubuntu point release
# drops one. libllvm19 is intentionally absent: not in 22.04 archive, and
# rustc-1.83 ships its codegen LLVM inside the libstd-rust deb tree.
LIB_PKGS=(
    libssh2-1
    libcurl3-gnutls
    libgit2-1.1
    libssl3
    libhttp-parser2.9
    libmbedtls14
    libmbedcrypto7
    libmbedx509-1
    libnghttp2-14
    librtmp1
    libpsl5
    libssh-4
    libgssapi-krb5-2
    libldap-2.5-0
    libk5crypto3
    libkrb5-3
    libkrb5support0
    libcom-err2
    libkeyutils1
    libsasl2-2
    libgnutls30
    libp11-kit0
    libtasn1-6
    libnettle8
    libhogweed6
    libgmp10
    libidn2-0
    libunistring2
    libffi8
    libzstd1
    libpcre2-8-0
    libsasl2-modules-db
    libdb5.3
    libbrotli1
    libgcrypt20
    libgpg-error0
    libcrypt1
    zlib1g
)

echo "[install-rust-sandbox] downloading ${#RUST_PKGS[@]} rust + ${#LIB_PKGS[@]} lib debs into ${PREFIX}"
# apt download tolerates missing packages with a non-fatal warning, so we
# pass them all in one shot and keep going. Some libs may not exist on
# every Ubuntu point release — that's fine if the sandbox already provides
# them via the base image.
apt download "${RUST_PKGS[@]}" "${LIB_PKGS[@]}" 2>&1 \
    | grep -vE '^(Get:|Fetched|WARNING:)' \
    || true

echo "[install-rust-sandbox] extracting debs into prefix"
shopt -s nullglob
for d in *.deb; do
    dpkg-deb -x "${d}" . 2>/dev/null || echo "[install-rust-sandbox] skip ${d}"
done

# Sanity-check all four tools resolve their shared libs.
RUST_BIN="${PREFIX}/usr/lib/rust-${RUST_VER}/bin"
RUST_LIB="${PREFIX}/usr/lib/rust-${RUST_VER}/lib"
SYS_LIB="${PREFIX}/usr/lib/x86_64-linux-gnu"
EXTRA_LIB="${PREFIX}/usr/lib"

export PATH="${RUST_BIN}:${PREFIX}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${SYS_LIB}:${RUST_LIB}:${EXTRA_LIB}"

OVERALL=0
for tool in rustc cargo rustfmt; do
    if ! "${RUST_BIN}/${tool}" --version >/dev/null 2>&1; then
        echo "[install-rust-sandbox] FAIL: ${tool} cannot start (missing shared lib?)" >&2
        ldd "${RUST_BIN}/${tool}" 2>&1 | grep "not found" >&2 || true
        OVERALL=1
    fi
done

# clippy is invoked as `cargo clippy`, which spawns clippy-driver from
# RUST_BIN; verify the driver itself loads.
if ! "${RUST_BIN}/clippy-driver" --version >/dev/null 2>&1; then
    echo "[install-rust-sandbox] FAIL: clippy-driver cannot start" >&2
    OVERALL=1
fi

if [ "${OVERALL}" -ne 0 ]; then
    exit 1
fi

# Write a sourceable env file so callers don't have to remember the export
# incantation. Path is stable so memory / docs can reference it.
cat > "${PREFIX}/env" <<EOF
# Source this to put the sandbox Rust toolchain on PATH.
# Generated by scripts/install-rust-sandbox.sh
export PATH="${RUST_BIN}:${PREFIX}/usr/bin:\${PATH}"
export LD_LIBRARY_PATH="${SYS_LIB}:${RUST_LIB}:${EXTRA_LIB}\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
EOF

echo
echo "[install-rust-sandbox] OK"
"${RUST_BIN}/rustc" --version
"${RUST_BIN}/cargo" --version
"${RUST_BIN}/rustfmt" --version
"${RUST_BIN}/clippy-driver" --version
echo
echo "[install-rust-sandbox] to use this toolchain in the current shell:"
echo "    source ${PREFIX}/env"
